/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_wzh_amrcodec_encoder_AmrEncoder */

#ifndef _Included_cn_wzh_amrcodec_encoder_AmrEncoder
#define _Included_cn_wzh_amrcodec_encoder_AmrEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_wzh_amrcodec_encoder_AmrEncoder
 * Method:    initEncAmr
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_cn_wzh_amrcodec_encoder_AmrEncoder_initEncAmr
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_wzh_amrcodec_encoder_AmrEncoder
 * Method:    exitEncAmr
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_wzh_amrcodec_encoder_AmrEncoder_exitEncAmr
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_wzh_amrcodec_encoder_AmrEncoder
 * Method:    encodeAmr
 * Signature: (Lcn/wzh/amrcodec/encoder/AmrMode;[S[B)I
 */
JNIEXPORT jint JNICALL Java_cn_wzh_amrcodec_encoder_AmrEncoder_encodeAmr
  (JNIEnv *, jclass, jobject, jshortArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
