/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_wzh_amrcodec_decoder_AmrDecoder */

#ifndef _Included_cn_wzh_amrcodec_decoder_AmrDecoder
#define _Included_cn_wzh_amrcodec_decoder_AmrDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_wzh_amrcodec_decoder_AmrDecoder
 * Method:    initDecamr
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_cn_wzh_amrcodec_decoder_AmrDecoder_initDecamr
  (JNIEnv *, jclass);

/*
 * Class:     cn_wzh_amrcodec_decoder_AmrDecoder
 * Method:    exitDecAmr
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_cn_wzh_amrcodec_decoder_AmrDecoder_exitDecAmr
  (JNIEnv *, jclass, jint);

/*
 * Class:     cn_wzh_amrcodec_decoder_AmrDecoder
 * Method:    decodeAmr
 * Signature: (I[B[SI)V
 */
JNIEXPORT void JNICALL Java_cn_wzh_amrcodec_decoder_AmrDecoder_decodeAmr
  (JNIEnv *, jclass, jint, jbyteArray, jshortArray, jint);

#ifdef __cplusplus
}
#endif
#endif
